[package]
name = "tak"
version = "0.2.0"
license = "GPL-3.0-or-later"
edition = "2021"

[features]
default = ["fixed-rng"]
deep-stacks = []
fixed-rng = []

[dependencies]
once_cell = "1.16"
rand = "0.8"
regex = "1.7"
tracing = "0.1"