[package]
name = "analysis"
version = "0.1.0"
license = "GPL-3.0-or-later"
edition = "2021"

[features]
deep-stacks = ["tak/deep-stacks"]

[dependencies]
ann = { path = "../ann" }
once_cell = "1.16"
tak = { path = "../tak" }
tracing = "0.1"

[dev-dependencies]
criterion = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lib]
bench = false

[[bench]]
name = "evaluation"
harness = false

[[bin]]
name = "extract_states"