[package]
name = "analysis"
version = "0.1.0"
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
once_cell = "1.16"
rand = "0.8"
rand_core = "0.6"
tak = { path = "../tak" }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }